version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:10.3
    ports:
      - "2345:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
  minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: 'iitu'
      MINIO_ROOT_PASSWORD: 'iitu_pass'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
      MINIO_ACCESS_KEY: 'iitu_accessKey'
      MINIO_SECRET_KEY: 'iitu_secretKey777'
    command: minio server /data
